Use Flask configuration framework
cal-itp/eligibility-server pull request #119
Opened 2022-08-10 02:38 UTC by angela-tran

Closes #109 

### Changes
 - Replaces direct usage of `settings` with `app.config` instead
 - Loads settings into `app.config` using `from_object`
 - Calls `app.config.from_envvar("ELIGIBILITY_SERVER_SETTINGS")` to allow optional overrides
 - Refactors tests to use a config fixture which can have its values changed
 - Deletes `test_settings.py` since now we're just using Flask's configuration framework
 - Updates docs

### ⚠️ Devs should update their .env files
Move any custom settings to `config/sample.py`, and change your .env file to simply set `ELIGIBILITY_SERVER_SETTINGS=../config/sample.py`.

2022-08-10 02:46 UTC, angela-tran commented
I anticipate needing to resolve merge conflicts with #116

2022-08-10 23:21 UTC, machikoyasuda approved these changes

2022-08-11 15:14 UTC, thekaveman commented
Taking a look. Will wait for the eventual rebase 😅 before submitting a review.

2022-08-15 23:18 UTC, thekaveman commented on config/sample.py
> +IMPORT_FILE_PATH = "data/server.csv"
Can we add an entry to `.gitignore` for other files in this directory? That way we can have local testing configs and not have to worry about git looking at them.

2022-08-15 23:53 UTC, machikoyasuda requested changes
One change:

Add `"python.defaultInterpreterPath": "/usr/local/bin/python",` to the VS Code `settings.json` file. 

Changing this allows my app to open in debug mode.

2022-08-16 00:27 UTC, angela-tran commented on config/sample.py
> +IMPORT_FILE_PATH = "data/server.csv"
Updated `.gitignore` in [d86d7ea](https://github.com/cal-itp/eligibility-server/pull/119/commits/d86d7ea3f159faf9d297360bd1f23b2845e6c79c)

2022-08-16 00:28 UTC, thekaveman approved these changes

2022-08-16 00:28 UTC, thekaveman approved these changes

2022-08-16 00:29 UTC, angela-tran commented
Sorry @thekaveman , I hit re-request right as you approved 😅

2022-08-16 00:48 UTC, machikoyasuda approved these changes

2022-08-16 16:22 UTC, merged