Refactor: organize application as a package
cal-itp/eligibility-server pull request #140
Opened 2022-08-31 00:44 UTC by angela-tran

Part of #131 

This PR makes changes to the organization of our code so that 
 - database-related code is grouped together 
 - our application can be imported as a package. 

This should allow us to move towards using the app factory pattern, which in turn should move us towards using a separate database when testing.

Note that the `setup.py` and `teardown.py` scripts for modifying the database were converted into `click` commands since that's the approach shown in [Flask documentation](https://flask.palletsprojects.com/en/2.2.x/tutorial/database/#id3).

2022-08-31 20:29 UTC, machikoyasuda requested changes
Small documentation change.

I ran and tested:
- Rebuilt the container off of `main` branch
- Ran `pip install -r requirements.txt`, `flask init-db`
- Ran and passed all tests
- Opened `http://localhost:5000/healthcheck`, `http://localhost:5000/publickey`
- Tested `flask drop-db`

2022-08-31 20:29 UTC, machikoyasuda commented on docs/getting-started.md
> +flask drop-db
Line 68 of this doc states: ```Starting the Dev Container will run `bin/init.sh`, which runs `setup.py` and starts the Flask app. The `setup.py` script creates the database and imports and saves users
based on the configured settings.```

It should now read that `bin/init.sh` runs `flask init-db` , which runs `db/setup.py` (or something like this...)

2022-08-31 21:24 UTC, machikoyasuda commented
I believe this PR also closes https://github.com/cal-itp/eligibility-server/issues/139

2022-09-01 00:22 UTC, thekaveman commented
👀 Started reading through this tonight, will finish a little later or tomorrow!

2022-09-01 20:24 UTC, thekaveman requested changes
This looks like a good direction overall.

I'm not totally thrilled with the `Database` class (nothing you did in this PR) - it feels weird, we called it that in the past because it literally was the hardcoded database. Now it's just that `check_user` function... which is really doing the eligibility check? Oh well. Not too worried about this for now.

Left a few comments inline, a few areas we need some changes and a few potential cleanups/reorgs.

2022-09-01 20:24 UTC, thekaveman commented on setup.py
> +        "flask",
I think here we want to list everything from `requirements.txt`, right?

I've done it like this in the past: https://github.com/compilerla/intake-html-table/blob/main/setup.py#L3

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/db/setup.py
> +import click
I didn't see `click` added to the requirements.txt?

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/db/teardown.py
> +            click.echo("Database does not exist.")
I would almost suggest combining `teardown.py` into `setup.py`, we still have different commands so it seems unnecessary to separate the modules since we aren't calling them directly anymore (`python setup.py/teardown.py`)

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/verify.py
> +from flask import abort, current_app
I like this approach, feels way cleaner than `app.app.something`

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/db/models.py
> +def init_app(app):
This feels like a strange module for the initialization of the database. Would it make more sense in `__init__.py`?

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/db/setup.py
> +def save_users(db, User, sub: str, name: str, types: str):
I'm confused we pass in the `User` class here, when it is imported globally at the top?

2022-09-01 20:24 UTC, thekaveman commented on eligibility_server/verify.py
> +        if current_app.config["INPUT_HASH_ALGO"] != "":
Going to create a follow-up issue to hide all these settings keys in a config object that we can import and use its attribute, e.g. `config.hash_algo`

2022-09-01 20:33 UTC, angela-tran commented
Thanks @machikoyasuda and @thekaveman for your thorough reviews! I agree with the things you pointed out and will work through these items.

2022-09-01 20:34 UTC, angela-tran commented on eligibility_server/db/setup.py
> +import click
Yeah, that is because `click` gets installed too when you install `flask`.

(https://flask.palletsprojects.com/en/2.2.x/installation/#dependencies)

2022-09-01 20:34 UTC, thekaveman commented on eligibility_server/db/setup.py
> +import click
I had no idea!

2022-09-01 20:36 UTC, angela-tran commented on eligibility_server/db/setup.py
> +def save_users(db, User, sub: str, name: str, types: str):
Oops, I think this is leftover from an intermediate cleanup state I was in. Thanks for catching this! I will clean up.

2022-09-02 20:45 UTC, angela-tran commented on docs/getting-started.md
> +flask drop-db
Resolved in https://github.com/cal-itp/eligibility-server/pull/140/commits/75dea8ed2b3e9c1ea6d8c306b412baa5333f65e1

2022-09-02 22:05 UTC, angela-tran commented on eligibility_server/verify.py
> +        if current_app.config["INPUT_HASH_ALGO"] != "":
I think this can be resolved since #142 has been created

2022-09-02 22:09 UTC, angela-tran commented
@thekaveman I made some changes based on your feedback. Also, I agree with this:

> I'm not totally thrilled with the `Database` class (nothing you did in this PR) - it feels weird, we called it that in the past because it literally was the hardcoded database. Now it's just that `check_user` function... which is really doing the eligibility check? Oh well. Not too worried about this for now.

Should I try to move the `check_user` logic into the `verify` module as a part of this PR?

2022-09-02 22:17 UTC, thekaveman requested changes
All of my comments below are mostly stylistic and don't _require_ any changes.

But one thing that should be addressed: *We want the Docker app container to install this package!*

Need a line in the `Dockerfile` like:


```docker
RUN pip install -e .
```

Obviously the source and `setup.py` need to the in the image layer for this to work, so may need to adjust how/where `pip install` happens, or just do it a second time if that's preferable.

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/app.py
>  from .keypair import get_server_public_key
It might make sense to use the package as the import source now:

```python
from eligibility_server import db
from eligibility_server.verify import Verify
from eligibility_server.keypair import get_server_public_key
```

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/db/database.py
> +from .models import User
Thoughts on the more verbose/explicit:

```python
from eligibility_server.db.models import User
```

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/db/models.py
> +from . import db
Same comment on import style/source

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/verify.py
Same comment on import style/source

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/db/__init__.py
> -class Database:
FWIW I wasn't necessarily saying this class should move from here, just that it is a weird name/class.

The import `from eligibility_server.db.database import Database` is a little clunky, but that's fine.

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/app.py
> +db.init_app(app)
👍

2022-09-02 22:17 UTC, thekaveman commented on eligibility_server/verify.py
> +from .db.database import Database
^ little clunky (3x database!)

2022-09-02 22:17 UTC, thekaveman commented on tests/test_database.py
> +from eligibility_server.db.database import Database
^ another 3x database

2022-09-02 22:18 UTC, thekaveman commented
> @thekaveman I made some changes based on your feedback. Also, I agree with this:
> 
> > I'm not totally thrilled with the `Database` class (nothing you did in this PR) - it feels weird, we called it that in the past because it literally was the hardcoded database. Now it's just that `check_user` function... which is really doing the eligibility check? Oh well. Not too worried about this for now.
> 
> Should I try to move the `check_user` logic into the `verify` module as a part of this PR?

Didn't see this comment before leaving my review - but yeah that could be a better place for it! Maybe turn `verify` into a sub-package with `api.py` and `somethingelse.py`?

2022-09-02 22:22 UTC, thekaveman commented on setup.py
> +    "Programming Language :: Python :: 3.9",
Technically 3.10 could go here too.... seems safe to just say `3` and not specify all the minor versions

2022-09-02 22:22 UTC, thekaveman commented on setup.py
> +    python_requires=">=3.7",
^^ Especially in combination with this min version

2022-09-07 03:20 UTC, angela-tran commented on tests/test_database.py
> -"""
I was going to say let's hold off on refactoring these tests until we get a test database going, but on second thought, let me try something

2022-09-07 03:33 UTC, angela-tran commented on tests/test_database.py
> -"""
I was able to port these tests over to using an instance of `Verify` instead of `Database`

2022-09-07 21:36 UTC, thekaveman approved these changes
Looks great!

* All tests passed locally
* The package is installed (in a python REPL session I could `import eligibility_server`)
* `/healthcheck`, `/publickey`, `/verify` return expected results

2022-09-07 21:55 UTC, machikoyasuda approved these changes

2022-09-07 21:56 UTC, merged