WIP
cal-itp/eligibility-server pull request #19
Opened 2021-10-04 21:42 UTC by machikoyasuda

2021-10-04 22:09 UTC, machikoyasuda commented
At the moment I'm running this PR's dev container locally with this change:
![image](https://user-images.githubusercontent.com/3673236/135931520-4e3abbf9-ea8a-4aa7-b1a3-9f2e9ea5c776.png)

2021-10-05 00:48 UTC, machikoyasuda commented
Tried:

```bash
docker-compose run --rm -e DEBUGGER=True -e FLASK_APP=eligibility_server/app.py -e FLASK_ENV=development --service-ports dev python -m debugpy --wait-for-client --listen 0.0.0.0:5678 eligibility_server/app.py
```

and added a breakpoint in 

```python
if __name__ == "__main__":
    print(app)
    print("STUFF")
    breakpoint()
    app.run(host="0.0.0.0", debug=True)  # nosec
```

I was able to get the VS Code debugger working and look into the `app` var, etc., but - once I clicked ▶️, the server broke.


```bash
➜  eligibility-server git:(chore/move-into-folder) ✗ docker-compose run --rm -e DEBUGGER=True -e FLASK_APP=eligibility_server/app.py -e FLASK_ENV=development --service-ports dev python -m debugpy --wait-for-client --listen 0.0.0.0:5678 eligibility_server/app.py
Creating eligibility-server_dev_run ... done
<Flask 'app'>
STUFF
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.0.2:5000/ (Press CTRL+C to quit)
 * Restarting with stat
No module named app
```

2021-10-05 06:28 UTC, thekaveman commented
So I just came across this: https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app-in-the-debugger

Which makes this whole thing much easier! I feel like this is new, `debugpy` is built in now!? 🤷 

So two tricks that got this working for me:

**`.vscode/launch.json`** was slightly different from the above docs, but not by much:

```jsonc
{
  "name": "Flask: Eligibility Verification Server",
  "type": "python",
  "request": "launch",
  "module": "flask",
  "args": [
    "run",
    "--host",
    "0.0.0.0"
  ],
  "env": {
    "FLASK_DEBUG": "1",
    "FLASK_ENV": "development"
  }
}
```

This now starts the server on-demand with `F5`, and watch/reload is also active! Possible to start/stop/restart as well.

**`docker-compose`** got much simpler:

```yaml
dev:
  build:
    context: .
    dockerfile: Dockerfile.dev
  command: sleep infinity
  image: eligibility_server:dev
  ports:
    - 5000
  volumes:
    - ./:/home/calitp/app/
```

`command: sleep infinity` ensures the devcontainer continues to run even if the server code crashes/dies, or when debug mode is stopped.

2021-10-05 06:31 UTC, thekaveman commented
There's a similar write-up for Django, which I tried with `benefits` and... it worked! 

https://code.visualstudio.com/docs/python/tutorial-django#_create-a-debugger-launch-profile

2021-10-05 19:31 UTC, thekaveman requested changes
Great job! Few small changes, added some links to more info about Docker entrypoint/command.

2021-10-05 19:31 UTC, thekaveman commented on .vscode/launch.json
> +                "FLASK_APP": "eligibility_server/app.py"
We can remove the `FLASK_APP` variable since it's already baked into the image.

2021-10-05 19:31 UTC, thekaveman commented on Dockerfile
> +ENV FLASK_APP=eligibility_server/app.py
Move this variable above with the first `ENV` statement. 1) so they are all grouped together and 2) so the variable is available to later layers in the Docker build process (not as relevant for this variable, but good to keep in mind).

2021-10-05 19:31 UTC, thekaveman commented on docker-compose.yml
> +    command: sleep infinity
In `benefits` I had to add [`entrypoint: []`](https://github.com/cal-itp/benefits/blob/refactor-debugger/localhost/docker-compose.yml#L37) to ensure the container's entrypoint was null, since it is [set explicitly in the parent Dockerfile](https://github.com/cal-itp/benefits/blob/dev/Dockerfile#L50).

For `eligibility-server` it works without, since the container's entrypoint is already null. But might be a good idea to add it anyway to guard against future breakage if the entrypoint changes.

[Decent answer in SO](https://stackoverflow.com/a/41676550/453168) talking about differences between entrypoint and command.

[Docker docs on `ENTRYPOINT`](https://docs.docker.com/engine/reference/builder/#entrypoint) in Dockerfile; `entrypoint` in docker-compose.yml works the same way. As do `CMD` in Dockerfile and `command` in docker-compse.yml.

2021-10-05 19:31 UTC, thekaveman commented on docker-compose.yml
> +      - 5000
Nice. This partially solves #9!

2021-10-05 20:12 UTC, thekaveman requested changes
Forgot to add:

You can remove `debugpy` from the [`requirements.txt`](https://github.com/cal-itp/eligibility-server/blob/main/requirements.txt#L2) file too!

2021-10-05 20:27 UTC, thekaveman approved these changes
🚀 🎸

2021-10-05 20:29 UTC, merged