WIP - Setting up .devcontainer
cal-itp/eligibility-server pull request #2
Opened 2021-09-28 19:31 UTC by machikoyasuda

2021-09-28 19:47 UTC, machikoyasuda commented
![image](https://user-images.githubusercontent.com/3673236/135155558-ece22d68-cb03-4ac7-8ca4-f0911536068c.png)
![image](https://user-images.githubusercontent.com/3673236/135155576-b1a82cd8-876f-498b-b62f-2b556c8d929f.png)
2 issues so far with this setup:

1. No Git
2. No permissions to save files!

2021-09-29 22:55 UTC, thekaveman requested changes
Looking great so far! I was able to get the devcontainer running locally and hit a breakpoint with debug mode active.

I made a few suggestions, nothing major. There was one minor fix to the docs.

2021-09-29 22:55 UTC, thekaveman commented on .pyup.yml
> +# pyup.io config file
Let's maybe leave this file out until (if) we configure this repo with pyup.io

2021-09-29 22:55 UTC, thekaveman commented on README.md
> +docker compose build
If we don't specify which service to build, Compose tries to build all the services in the file. But it can't build the `dev` service until after the `server` service is finished building, so this fails.

Just need to specify which service to build: 

```bash
docker compose build server
```

2021-09-29 22:55 UTC, thekaveman commented on app.py
>  @app.route("/")
We can mirror a pattern in the `benefits` app here:

Instead of this Hello World route, let's have a route for `/healthcheck` that just returns the string "Healthy" (no HTML tags needed). This is what we do here: https://github.com/cal-itp/benefits/blob/dev/benefits/core/middleware.py#L45 and it's used by AWS to see if the app is alive.

2021-09-30 21:59 UTC, thekaveman approved these changes

2021-09-30 22:51 UTC, merged