Feat(Terraform): front door
cal-itp/eligibility-server pull request #222
Opened 2022-11-30 16:44 UTC by angela-tran

Closes #208

2022-11-30 23:00 UTC, angela-tran commented on terraform/variables.tf
> +variable "IP_ADDRESS_WHITELIST_PROD" {
Any ideas for a better way to do this?

2022-12-01 19:31 UTC, angela-tran commented on terraform/variables.tf
> +variable "IP_ADDRESS_WHITELIST_PROD" {
We could go with this for now and also leave #213 open for this to be refactored.

2022-12-01 22:54 UTC, thekaveman commented on terraform/variables.tf
> +variable "IP_ADDRESS_WHITELIST_PROD" {
I think it's fine to leave a refactor for #213, this seems like a good approach to get started.

2022-12-02 16:44 UTC, afeld requested changes
Nice work! Just one blocker; the rest are optional. Questions:

- Thoughts about adding a bit of documentation around why we're using Front Door? Or sufficient to have [this comment](https://github.com/cal-itp/eligibility-server/issues/208#issuecomment-1332859410)?
- We are allowing the availability tests through, which is good… What do we think about having a smoke test to ensure other requests are _not_ allowed? Could do this through [a GitHub Action](https://github.com/marketplace/actions/http-status) or [Azure Pipeline task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml).

2022-12-02 16:44 UTC, afeld commented on terraform/app_service.tf
> +    }
Mind adding a note about this being required to the `uptime` module README? Also a note in the README in this directory about access being restricted, so future folks aren't confused about getting 403s?

2022-12-02 16:44 UTC, afeld commented on terraform/front_door.tf
> +  session_affinity_enabled = true
Minor: Since (I don't think) we're using cookies, not sure this is necessary.

```suggestion
```

2022-12-02 16:44 UTC, afeld commented on terraform/front_door.tf
> +  priority                       = 1
Minor: The numbers above are all same as [the defaults](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_origin#arguments-reference), so could be removed for brevity. Fine either way.

2022-12-02 16:44 UTC, afeld commented on terraform/front_door.tf
> +}
Thoughts about allowing access to `/healthcheck` from any IP? Could be useful for troubleshooting, but maybe not worth the extra complexity / attack surface.

2022-12-02 21:55 UTC, thekaveman commented on terraform/front_door.tf
> +}
Agreed this could be useful, not sure how hard it would be to add here

2022-12-05 20:15 UTC, angela-tran commented on terraform/front_door.tf
> +  session_affinity_enabled = true
Done in f1bd673da090fbd303eb6636ff1899f81501114e

2022-12-05 20:15 UTC, angela-tran commented on terraform/front_door.tf
> +  priority                       = 1
Done in 0c160c72a731e6565dc64b3e86ac2aba4354040f

2022-12-05 20:16 UTC, angela-tran commented on terraform/front_door.tf
> +}
I was able to get a working configuration the `dev` environment. Defined the Terraform equivalent in 5a28a9bcece6cb5084dbbde702768bd1c030a774

2022-12-05 20:18 UTC, angela-tran commented
> Thoughts about adding a bit of documentation around why we're using Front Door? Or sufficient to have https://github.com/cal-itp/eligibility-server/issues/208#issuecomment-1332859410?

I added a section to the README in 5e6f74e68084f4b5c47019325b489525876c8796

2022-12-05 20:18 UTC, angela-tran commented
> We are allowing the availability tests through, which is good… What do we think about having a smoke test to ensure other requests are not allowed? Could do this through [a GitHub Action](https://github.com/marketplace/actions/http-status) or [Azure Pipeline task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml).

Any objection to creating a new issue for this?

2022-12-05 22:55 UTC, thekaveman reviewed
Left some questions - not necessarily required changes, but hoping for some additional clarity ahead of Approval.

2022-12-05 22:55 UTC, thekaveman commented on terraform/front_door.tf
> +  load_balancing {}
why the empty `load_balancing` section here? (maybe leave a small comment)

2022-12-05 22:55 UTC, thekaveman commented on terraform/front_door.tf
> +  custom_block_response_body        = base64encode("Blocked")
The term most often associated with `403` is _Forbidden_: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2022-12-05 22:55 UTC, thekaveman commented on terraform/front_door.tf
> +      operator       = "EndsWith"
This mean any request that ends with `/healthcheck` will go through, right?

Should we do an exact match here to shore up this one exception and make sure it is the only one? I think `Equals` is the `operator` for that: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_firewall_policy#operator

2022-12-05 22:55 UTC, thekaveman commented on terraform/front_door.tf
> +      operator           = "Contains"
Same question on this `operator`: is `Contains` too loose here? Can't we expect an exact `Equals` match for the IP address and not allow anything else?

2022-12-06 20:41 UTC, afeld reviewed
We currently have the uptime check accessing the App Service directly, not through Front Door. Thinking we should change it to the latter to make it end-to-end. This would remove the need for allowing those requests to the App Service, though not a big deal to leave them.

2022-12-06 21:46 UTC, thekaveman commented
> We currently have the uptime check accessing the App Service directly, not through Front Door. Thinking we should change it to the latter to make it end-to-end. This would remove the need for allowing those requests to the App Service, though not a big deal to leave them.

Seems like a good follow-up! #223

2022-12-06 22:29 UTC, angela-tran commented on terraform/front_door.tf
> +  load_balancing {}
Added a comment in 8ed904ee58246672abc6deeaf262ba237096e7b0

2022-12-06 22:30 UTC, angela-tran commented on terraform/front_door.tf
> +      operator       = "EndsWith"
Done in f9b039d31aef260bdc9fce1633817a2f43a0193d

2022-12-06 22:39 UTC, thekaveman approved these changes
Looks like a great start, thank you @angela-tran! We can worry about deployment when you're back 😄

2022-12-13 21:21 UTC, angela-tran commented
@afeld let me know if there's anything else to change here. This needs your approval before I can merge. Thanks!

2022-12-13 22:05 UTC, afeld approved these changes

2022-12-13 23:28 UTC, merged