Refactor: use eligibility-api
cal-itp/eligibility-server pull request #228
Opened 2022-12-14 17:22 UTC by angela-tran

Closes #38 

This PR makes the minimal changes needed for eligibility-server to use the eligibility-api.
It also removes `jwcrypto` from the app container's dependencies.

### Rebuilding
Make sure to run
```
./bin/build.sh
```
before re-opening the devcontainer so that these changes to the app container's `requirements.txt` are used.

2022-12-14 17:27 UTC, angela-tran commented
Going to rebase this to get #227

2022-12-14 17:43 UTC, machikoyasuda commented
Hooray for reducing dependencies!!!

2022-12-21 23:03 UTC, thekaveman requested changes
Really nice work! This is a good start to use the API library. Next steps will be to publish the package to PyPI and use that reference, a la cal-itp/eligibility-api#22

One minor change to the tests to align more closely with how Server is working now.

2022-12-22 19:27 UTC, angela-tran commented
Rebasing to resolve merge conflict

2022-12-22 19:39 UTC, angela-tran commented on tests/test_keypair.py
> +    key = jwk.JWK.from_pem(_read_key_file(sample_key_path_local))
Thanks! Done in [dc04d84](https://github.com/cal-itp/eligibility-server/pull/228/commits/dc04d84bad7fe785479ae068cda5d08da90366ef)

2022-12-22 20:08 UTC, thekaveman approved these changes
Very nice!

2022-12-22 20:16 UTC, merged