Create Database, Verify classes
cal-itp/eligibility-server pull request #32
Opened 2021-10-07 22:40 UTC by machikoyasuda

closes #29 

* move Database class, Verify class into their own files
* add very basic Verify route spec
* creates Settings file that has a list of configs
* create and use Settings variables for hard-coded strings/booleans/numbers

2021-10-07 23:05 UTC, machikoyasuda commented on eligibility_server/verify.py
> +                    iss="THIS IS STUBBED",
I need to figure out how to either import `app` into this file from `eligibility_server.app` or just import `app.name`.

Currently getting this error when trying to `import eligibility_server.app`:

```bash
$ coverage run -m pytest -q --disable-warnings
ImportError while loading conftest '/home/calitp/app/tests/conftest.py'.
tests/conftest.py:3: in <module>
    from eligibility_server.app import app
eligibility_server/app.py:7: in <module>
    from eligibility_server.verify import Verify
eligibility_server/verify.py:13: in <module>
    from eligibility_server.app import app_name
E   ImportError: cannot import name 'app_name' from partially initialized module 'eligibility_server.app' (most likely due to a circular import) (/home/calitp/app/eligibility_server/app.py)
```

2021-10-13 23:01 UTC, thekaveman commented on eligibility_server/app.py
> +from eligibility_server.verify import Verify
It's conventional to a put a blank line between each set of imports, in the following order:

```python
# system libraries
import datetime
import json

# vendor libraries
import flask
import jwcrypto

# local project modules
from . import settings
from .verify import Verify
```

Notice the syntax on those final local imports; when importing from within the same directory, they can be a bit of a shortcut.

2021-10-13 23:13 UTC, thekaveman commented on eligibility_server/app.py
>  api = Api(app)
Let's move the `api` creation down after the healthcheck, closer to its resource registration. This way:

1. The `app` is created and configured first
2. Then the `api` is created and configured second

And each step/phase is grouped together in the code.

Also, it is conventional for module-level statements to be separated by double blank lines to make them stand apart from other module-level stuff. [`black`](https://black.readthedocs.io) and the pre-commit hooks should do most of this automatically, but it misses things sometimes. 

```python
"""
Docstring
"""

import library


module_var1 = something()
module_var1.setting = "1"


module_var2 = something_else()


def func():
    # do something


class Cls:
    # define me


if __name__ == "__main__":
    # etc.
```

2021-10-13 23:14 UTC, thekaveman commented on eligibility_server/app.py
>      app.run(host="0.0.0.0", debug=True)  # nosec
We can move both of these hardcoded values to `settings`!

2021-10-13 23:52 UTC, machikoyasuda commented on eligibility_server/app.py
>  api = Api(app)
I _think_ this next commit resolved this: https://github.com/cal-itp/eligibility-server/pull/32/commits/feba866630f0608f37015a1877c0c38168278f5f

2021-10-13 23:57 UTC, thekaveman commented on eligibility_server/app.py
> +    app.run(host=settings.HOST, debug=True)  # nosec
One more! `debug=True` 😄

2021-10-13 23:59 UTC, thekaveman commented on eligibility_server/app.py
>  api = Api(app)
yep! perfect

2021-10-14 01:15 UTC, thekaveman requested changes

2021-10-14 01:15 UTC, thekaveman commented on eligibility_server/app.py
> +if __name__ == settings.__name__:
Sorry, I'm being pedantic now... 

`"__main__"` is the value of the module's `__name__` variable given by Python, when the module file is run from the command line a la `python file.py`. It doesn't need to be a setting as it's configured by Python automatically and doesn't change.

2021-10-14 19:55 UTC, merged