Feat: deploy for pre-release or release
cal-itp/eligibility-server pull request #329
Opened 2023-09-27 00:35 UTC by angela-tran

Closes #286

2023-09-29 20:20 UTC, angela-tran commented on .github/workflows/docker-publish.yml
>              ghcr.io/${{ github.repository }}:${{ github.sha }}
Because we are in an interim state of still doing merge-based deployments, the first two values in this list will be the same... I'm not sure if the `docker/build-push-action@v5` action will allow that.

2023-09-29 20:25 UTC, angela-tran commented on .github/workflows/docker-publish.yml
> +    if: always() && !cancelled() && (github.event_name != 'release' || needs.test.result == 'success')
`always()` is needed here because even if `test` didn't run, we still want this to run. 
`!cancelled()` is needed because if the whole workflow was cancelled, we don't want this to run.
`github.event_name != 'release' || needs.test.result == 'success')` is needed because if `test` _did_ run, we only want this to run if `test` succeeded.

2023-09-29 20:36 UTC, angela-tran commented on .github/workflows/docker-publish.yml
>              ghcr.io/${{ github.repository }}:${{ github.sha }}
There's not a really easy way to test this without just merging this and trying a merge-based deployment.

If we really do want to test this before merging though, it could be set up in a smaller experimental repo. It just takes some time to get it all set up.

2023-09-29 20:38 UTC, angela-tran commented
This is ready for review, but note that this is a stretch item for the sprint so it's ok if this doesn't get reviewed for a while

2023-09-29 20:44 UTC, thekaveman commented on .github/workflows/docker-publish.yml
> +    if: always() && !cancelled() && (github.event_name != 'release' || needs.test.result == 'success')
I'm not following the need for `always()` -- isn't that like saying `true AND x` which evaluates to whatever `x` is?

2023-09-29 21:28 UTC, angela-tran commented on .github/workflows/docker-publish.yml
> +    if: always() && !cancelled() && (github.event_name != 'release' || needs.test.result == 'success')
I think you are right that it is redundant! I tried it out myself to verify.

Removed it in 659c5c80f9fc658718c8fc1abb55b2c8c42c83f2

2023-09-29 21:33 UTC, thekaveman requested changes

2023-09-29 21:33 UTC, thekaveman commented on .github/workflows/docker-publish.yml
> +    if: (!cancelled() && (github.event_name != 'release' || needs.test.result == 'success'))
Great!

I think it would be useful to have a little comment here describing what you [said in this PR comment](https://github.com/cal-itp/eligibility-server/pull/329#discussion_r1341766075)

2023-09-29 21:37 UTC, thekaveman commented on .github/workflows/docker-publish.yml
> +  - DEPLOYMENT_ENVIRONMENT: ${{ github.event_name != 'release' && github.ref_name || github.event.release.prerelease && 'test' || 'prod' }}
Finally understand this 🤯 😨

2023-09-29 23:02 UTC, thekaveman approved these changes
LGTM!

I just ran this in my terminal, which makes me think the duplicate tag here won't be a problem:

```console
$ docker build --no-cache -t eligibility_server:main -t eligibility_server:main .
[+] Building 0.0s (0/0)                                                                                                                                              docker:default
[+] Building 46.0s (11/11) FINISHED                                                                                                                                  docker:default 
 => [internal] load build definition from Dockerfile                                                                                                                           6.0s 
 => => transferring dockerfile: 404B                                                                                                                                           0.0s 
 => [internal] load .dockerignore                                                                                                                                              6.4s 
 => => transferring context: 81B                                                                                                                                               0.0s 
 => [internal] load metadata for ghcr.io/cal-itp/docker-python-web:main                                                                                                        1.9s 
 => CACHED [1/6] FROM ghcr.io/cal-itp/docker-python-web:main@sha256:7a8a6bc350c5ebffd04b3855912abeb3fb8a1b23c8578ad47c4a463a16a6070c                                           0.0s 
 => [internal] load build context                                                                                                                                              0.8s
 => => transferring context: 674B                                                                                                                                              0.0s
 => [2/6] RUN python -m pip install --upgrade pip                                                                                                                              7.0s
 => [3/6] COPY bin bin                                                                                                                                                         0.4s
 => [4/6] COPY eligibility_server/ eligibility_server/                                                                                                                         0.3s
 => [5/6] COPY pyproject.toml pyproject.toml                                                                                                                                   0.2s
 => [6/6] RUN pip install -e .                                                                                                                                                28.1s
 => exporting to image                                                                                                                                                         0.8s 
 => => exporting layers                                                                                                                                                        0.7s 
 => => writing image sha256:97398d05669bda9f05d9a655dbd1f1e0b6c95aa5c22ba61e5e45a0d11df5c09e                                                                                   0.0s 
 => => naming to docker.io/library/eligibility_server:main
```

2023-10-02 16:05 UTC, angela-tran commented
> I just ran this in my terminal, which makes me think the duplicate tag here won't be a problem

Ooh, good idea to try that 👍

2023-10-02 16:06 UTC, merged