Refactor: remove role assignment from Terraform
cal-itp/eligibility-server pull request #359
Opened 2023-10-30 23:50 UTC by angela-tran

Part of #296 

We found that because the pipeline service principal defaults to having `Contributor` role, it is not able to create the role assignment for the ETL principal on the Storage Container. 

After some discussion, we decided we should remove the role assignment from being managed by Terraform / the pipeline, and it'll be a part of the manual creation steps to set up the role assignment.

This PR deletes the role configuration from Terraform and adds documentation for the manual steps.

### Pre-merge actions
For **MST**, we need to run `terraform state rm azurerm_role_assignment.velocity_etl[0]` so that Terraform "forgets" about the role and doesn't try to destroy it (see [docs on `rm`](https://developer.hashicorp.com/terraform/cli/commands/state/rm)). After merging, the `prod` pipeline should succeed, and there's nothing left to do.

For **SBMTD**, there's no pre-merge action to do. After merging, the `prod` pipeline should succeed since now there is no permissions error to run into. The last thing to do is to manually create the role assignment on the ETL service principal. Doing so requires the `Owner` role on your Azure account in the SBMTD subscription.

2023-10-30 23:57 UTC, angela-tran commented
There's a little more code cleanup to do

2023-10-31 15:47 UTC, thekaveman requested changes

2023-10-31 15:47 UTC, thekaveman commented on terraform/variables.tf
>  variable "AGENCY_CARD_DATA_ETL_FILE" {
I don't think we need this variable anymore either right?

2023-10-31 15:48 UTC, thekaveman requested changes
And let's also delete the unused variables from the agency-specific `azure-vars.yml` files.

2023-10-31 17:10 UTC, angela-tran commented on terraform/variables.tf
>  variable "AGENCY_CARD_DATA_ETL_FILE" {
Thanks for catching! I removed the variable and values in https://github.com/cal-itp/eligibility-server/pull/359/commits/83d5231d7f9510986f83ce3ed1de939c903c4683

2023-10-31 17:23 UTC, angela-tran commented
Successfully ran the `terraform state rm...` command for MST prod workspace:
```
C:\dev\eligibility-server\terraform>terraform state rm azurerm_role_assignment.velocity_etl[0]
Removed azurerm_role_assignment.velocity_etl[0]
Successfully removed 1 resource instance(s).
```

2023-10-31 17:28 UTC, thekaveman approved these changes

2023-10-31 17:29 UTC, merged