chore: create bug report github issue
cal-itp/eligibility-server pull request #475
Opened 2024-07-09 18:12 UTC by machikoyasuda

fixes #276 

I used the same exact template as Benefits: https://github.com/cal-itp/benefits/blob/dev/.github/ISSUE_TEMPLATE/bug-report.md

2024-07-09 22:49 UTC, machikoyasuda commented
Is there a way to override this Markdown Lint error? @thekaveman 

```
markdownlint.............................................................Failed
- hook id: markdownlint
- exit code: 1

.github/ISSUE_TEMPLATE/bug-report.md:7 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "A clear and concise descriptio..."]
```

2024-07-10 15:26 UTC, thekaveman commented
@machikoyasuda 

> Is there a way to override this Markdown Lint error? @thekaveman

Ah, annoying. Yes you can add the rule that is failing (`MD041`) to the [`.markdownlint.yaml`](https://github.com/cal-itp/eligibility-server/blob/main/.markdownlint.yaml) file in the root of this repo to ignore it.

2024-07-10 23:15 UTC, thekaveman approved these changes

2024-07-10 23:17 UTC, thekaveman requested changes
You know I'm thinking of a few things (sorry)

1. We don't really need the screenshots or device info here, as Server isn't used by end-users directly. Presumably those details would come from Benefits error logs/analytics etc.
2. We do want to know the environment(s): `dev`, `test`, `prod`, some combination? 
3. Also the agency: `mst`, `sbmtd`, both?

2024-07-10 23:51 UTC, thekaveman approved these changes

2024-07-10 23:54 UTC, merged