Refactor/tests marks
cal-itp/eligibility-server pull request #55
Opened 2022-01-14 00:37 UTC by machikoyasuda

WIP

2022-01-17 17:46 UTC, thekaveman requested changes
I'm liking the parameterized tests!

2022-01-17 17:46 UTC, thekaveman commented on .github/workflows/run-tests.yml
> +          set -a
It seems redundant to `set +a` then `set -a` right away... maybe just leave the final `set +a` for the end?

2022-01-18 18:57 UTC, angela-tran reviewed
The parameterization and the custom marks look good to me!

I agree with @thekaveman 's feedback that we could remove those redundant lines in the workflow.

2022-01-18 21:11 UTC, thekaveman approved these changes
🚀

2022-01-18 21:13 UTC, angela-tran approved these changes
👍

2022-01-18 21:14 UTC, merged