Move Docker files into .devcontainer
cal-itp/eligibility-server pull request #94
Opened 2022-05-25 21:43 UTC by machikoyasuda

closes #91 

## What this PR does
- Moves Docker and related files into .devcontainer, and updates files accordingly
- Updates docs with instruction to cd into .devcontainer

2022-05-25 21:44 UTC, machikoyasuda commented on .devcontainer/compose.yml
> +    build: ..
@thekaveman Are these changes necessary (to add the extra `.`) here and in `volumes:` and `context:`? I was not sure.

2022-05-25 22:09 UTC, thekaveman commented on .devcontainer/compose.yml
> +    build: ..
Yeah I think you do want these:

* `build: ..` tells Docker to build from the parent folder (e.g. not `.devcontainer/` but the root of the repo). This is what we want.
* `volumes:` with the mapping into `/home/calitp/app` is necessary to map your host machine repo into the devcontainer, so you can edit files and have that be reflected back to your host machine (where the files really live). Maybe not as necessary for `server`.

2022-05-25 22:13 UTC, thekaveman commented on .devcontainer/compose.yml
> +      dockerfile: .devcontainer/Dockerfile
Yeah `context: ..` here does the same as `build: ..` above. 

But since we're telling Docker to use a different Dockerfile, we have to use `context`.

`build` combines the two concepts and assumes you want to use the `Dockerfile` sitting in the `context` directory.

2022-05-27 00:04 UTC, thekaveman requested changes

2022-05-27 20:15 UTC, merged